# Generated by Django 4.2 on 2026-04-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_reset_token_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='district_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='province_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='ward_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_created',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
